version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports: 
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports: 
      - 9092:9092
    environment: 
      KAFKA_CREATE_TOPICS: "CreateUser:1:3" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"

  auth:
    ports:
      - 4000:4000
    env_file:
      - .env
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    container_name: auth
    image: caffeines/auth
    volumes:
      - /app/node_modules
      - ./auth:/app

  customer:
    ports:
      - 4001:4001
    env_file:
      - .env
    build:
      context: ./customer
      dockerfile: Dockerfile.dev
    container_name: customer
    image: caffeines/customer
    volumes:
      - /app/node_modules
      - ./customer:/app
